server.port=8080
management.endpoints.web.exposure.include=health
app.jwt.issuer=${COGNITO_ISSUER:https://cognito-idp.us-east-1.amazonaws.com/REEMPLAZAR_USER_POOL_ID}
app.jwt.client-id=${COGNITO_CLIENT_ID:REEMPLAZAR_CLIENT_ID}
