server.port=8080
management.endpoints.web.exposure.include=health

app.jwt.issuer=${COGNITO_ISSUER:https://cognito-idp.us-east-1.amazonaws.com/REEMPLAZAR_USER_POOL_ID}
app.jwt.client-id=${COGNITO_CLIENT_ID:REEMPLAZAR_CLIENT_ID}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/pedidos360?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
