name: Frontend Compile
on:
  push:
    branches: [main]
    paths: ['frontend/**', '.github/workflows/frontend_compile.yml']
  pull_request:
    paths: ['frontend/**', '.github/workflows/frontend_compile.yml']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Instalar dependencias
        working-directory: frontend
        run: npm install
      - name: Compilar React
        working-directory: frontend
        run: npm run build
